language: node_js
node_js:
  - "12"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  name: ycvcb123
  email: yangyang1991318@qq.com
  on:
    branch: main
